language: node_js

cache: npm

before_script:
  - npm run lint

jobs:
  include:
    - stage: release
      node_js: 'node'
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
