# Docker Swarm is required
version: '3.7'
services:
  orm:
    image: prismagraphql/prisma:1.31
    ports:
      - target: 4466
        published: 4466
        protocol: tcp
        mode: host
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: mongo
            uri: mongodb://prisma:prisma@db:27017/admin

    networks:
      database:

  db:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: prisma
      MONGO_INITDB_ROOT_PASSWORD: prisma
    volumes:
      - database_mongo:/var/lib/mongo
    networks:
      database:

networks:
  database:

volumes:
  database_mongo:
